apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # ECR에서 이미지를 가져오기 위한 인증키
      imagePullSecrets:
      - name: regcred
      # --- 여기까지 추가된 부분 ---
      containers:
      - name: backend
        image: 445516435241.dkr.ecr.ap-northeast-2.amazonaws.com/prod-app:98f4e5a1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32001
  type: NodePort